---

deb:
  apt:
    basic_packages:
      - git
      - wget
      - curl
      - vim
    unneeded_packages:
      - ppp
      - pppconfig
      - pppoeconf
      - libx11-data
      - xauth
      - libxmuu1
      - libxcb1
      - libx11-6
      - libxext6
      - linux-source

el:
  yum:
    basic_packages:
      - git
      - wget
      - curl
      - vim
    unneeded_packages:
      - cpp
      - kernel-devel
      - kernel-headers

suse:
  zypper:
    basic_packages:
      - git
      - wget
      - curl
      - vim

